import Head from 'next/head'
import Image from 'next/image'
import LoginPage from '../components/login'

export default function Home() {
  return (
    <div >
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
 
      <LoginPage/>
      <div > 
          <i className="fa-solid fa-check"></i><br/>
        I am just here working on building a full stack app for bloging and personal brand
      </div>
    </div>
  )
}
